<a href="https://colab.research.google.com/github/rohith7612/Generative-AI/blob/main/Vector_Conversion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# One hot encoding.

In [6]:
from sklearn.preprocessing import OneHotEncoder

sentence = "Taj Mahal is a beautiful monument"
words = sentence.lower().split()

words_reshaped = [[word] for word in words]

encoder = OneHotEncoder(sparse_output=False)
encoded = encoder.fit_transform(words_reshaped)

print(encoded)

[[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]]


# Bag of Words technique

In [3]:
from sklearn.feature_extraction.text import CountVectorizer

sentence = ["Taj Mahal is a beautiful monument"]

vectorizer = CountVectorizer()
bow = vectorizer.fit_transform(sentence)

print("Vocabulary:", vectorizer.vocabulary_)
print("Bag of Words Vector:", bow.toarray())

Vocabulary: {'taj': 4, 'mahal': 2, 'is': 1, 'beautiful': 0, 'monument': 3}
Bag of Words Vector: [[1 1 1 1 1]]


# BOW implementation using Practical SMSSPAM dataset.

In [8]:
import pandas as pd
messages = """ My dear young friends, education is the most powerful tool for transforming individuals and societies. In a rapidly changing world driven by science and technology, the role of learning has expanded beyond
classrooms and textbooks. Knowledge must be continuously updated through observation, experimentation,
and real-world problem solving. When students develop curiosity and the courage to question existing
ideas, they become creators of new solutions rather than mere followers of old paths.

The future of any nation depends on how its youth think, innovate, and act with responsibility.
Discipline and hard work form the foundation of success, but values such as honesty, empathy, and
service to society give true meaning to achievement. Challenges are an inevitable part of life,
yet every challenge carries within it the seed of opportunity. Those who learn to persevere with
confidence and determination will always find a way forward.

Dreams play a vital role in shaping human progress. They are not limited to personal ambition but
are connected to the collective growth of society. A dream becomes meaningful when it is supported
by clear goals, structured planning, and consistent effort. Great achievements in science, industry,
and governance have always emerged from individuals who dared to dream beyond limitations and work
relentlessly to turn vision into reality.

Technology has become a key driver of development in the modern era. From communication and healthcare
to education and agriculture, digital tools are reshaping how people live and work. However, technology
alone cannot guarantee progress. It must be guided by ethical thinking and a commitment to inclusive
growth. When innovation is aligned with human values, it has the power to uplift communities and reduce
inequality.

Leadership in the twenty-first century demands both intelligence and compassion. True leaders inspire
others through action, integrity, and humility rather than authority alone. They listen carefully,
learn continuously, and empower those around them to perform at their best. The responsibility of
leadership is not only to achieve success but also to create opportunities for others to succeed.

India’s journey towards becoming a knowledge-based economy requires active participation from its
youth, educators, scientists, and policymakers. By fostering a culture of research, creativity, and
collaboration, the nation can address complex global challenges. With unity of purpose and dedication
to excellence, the youth of today can build a future that is prosperous, sustainable, and driven by
innovation.
"""

# Data Cleaning and Preprocessing.

In [12]:
import nltk
import re
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem import SnowballStemmer
ss = SnowballStemmer('english')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [13]:
corpus = []
review = re.sub('[^a-zA-Z]', ' ', messages)
review = review.lower()
review = review.split()
review = [ss.stem(word) for word in review if not word in stopwords.words("english")]
review = " ".join(review)
corpus.append(review)

In [14]:
corpus

['dear young friend educ power tool transform individu societi rapid chang world driven scienc technolog role learn expand beyond classroom textbook knowledg must continu updat observ experiment real world problem solv student develop curios courag question exist idea becom creator new solut rather mere follow old path futur nation depend youth think innov act respons disciplin hard work form foundat success valu honesti empathi servic societi give true mean achiev challeng inevit part life yet everi challeng carri within seed opportun learn persever confid determin alway find way forward dream play vital role shape human progress limit person ambit connect collect growth societi dream becom meaning support clear goal structur plan consist effort great achiev scienc industri govern alway emerg individu dare dream beyond limit work relentless turn vision realiti technolog becom key driver develop modern era communic healthcar educ agricultur digit tool reshap peopl live work howev techn

# Creating Bag Of Words.

In [15]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=2500,binary=True)
X = cv.fit_transform(corpus).toarray()

# N-Grams Implementation

In [29]:
from sklearn.feature_extraction.text import CountVectorizer


corpus = """My dear young friends, education is the most powerful tool for transforming individuals and societies. In a rapidly changing world driven by science and technology, the role of learning has expanded beyond
classrooms and textbooks. Knowledge must be continuously updated through observation, experimentation,
and real-world problem solving. When students develop curiosity and the courage to question existing
ideas, they become creators of new solutions rather than mere followers of old paths.

The future of any nation depends on how its youth think, innovate, and act with responsibility.
Discipline and hard work form the foundation of success, but values such as honesty, empathy, and
service to society give true meaning to achievement. Challenges are an inevitable part of life,
yet every challenge carries within it the seed of opportunity. Those who learn to persevere with
confidence and determination will always find a way forward.

Dreams play a vital role in shaping human progress. They are not limited to personal ambition but
are connected to the collective growth of society. A dream becomes meaningful when it is supported
by clear goals, structured planning, and consistent effort. Great achievements in science, industry,
and governance have always emerged from individuals who dared to dream beyond limitations and work
relentlessly to turn vision into reality.

Technology has become a key driver of development in the modern era. From communication and healthcare
to education and agriculture, digital tools are reshaping how people live and work. However, technology
alone cannot guarantee progress. It must be guided by ethical thinking and a commitment to inclusive
growth. When innovation is aligned with human values, it has the power to uplift communities and reduce
inequality.

Leadership in the twenty-first century demands both intelligence and compassion. True leaders inspire
others through action, integrity, and humility rather than authority alone. They listen carefully,
learn continuously, and empower those around them to perform at their best. The responsibility of
leadership is not only to achieve success but also to create opportunities for others to succeed.

India’s journey towards becoming a knowledge-based economy requires active participation from its
youth, educators, scientists, and policymakers. By fostering a culture of research, creativity, and
collaboration, the nation can address complex global challenges. With unity of purpose and dedication
to excellence, the youth of today can build a future that is prosperous, sustainable, and driven by
innovation.
"""


In [24]:
import nltk
import re
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem import SnowballStemmer
ss = SnowballStemmer('english')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [25]:
corpus = []
review = re.sub('[^a-zA-Z]', ' ', messages)
review = review.lower()
review = review.split()
review = [ss.stem(word) for word in review if not word in stopwords.words("english")]
review = " ".join(review)
corpus.append(review)

In [26]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=2500,binary=True,ngram_range=(1,2))
x = cv.fit_transform(corpus).toarray()

In [28]:
cv.vocabulary_

{'dear': np.int64(99),
 'young': np.int64(419),
 'friend': np.int64(167),
 'educ': np.int64(127),
 'power': np.int64(297),
 'tool': np.int64(379),
 'transform': np.int64(384),
 'individu': np.int64(208),
 'societi': np.int64(347),
 'rapid': np.int64(311),
 'chang': np.int64(56),
 'world': np.int64(414),
 'driven': np.int64(120),
 'scienc': np.int64(336),
 'technolog': np.int64(368),
 'role': np.int64(333),
 'learn': np.int64(238),
 'expand': np.int64(149),
 'beyond': np.int64(39),
 'classroom': np.int64(58),
 'textbook': np.int64(372),
 'knowledg': np.int64(230),
 'must': np.int64(259),
 'continu': np.int64(82),
 'updat': np.int64(395),
 'observ': np.int64(267),
 'experiment': np.int64(151),
 'real': np.int64(316),
 'problem': np.int64(300),
 'solv': np.int64(353),
 'student': np.int64(357),
 'develop': np.int64(109),
 'curios': np.int64(95),
 'courag': np.int64(85),
 'question': np.int64(309),
 'exist': np.int64(147),
 'idea': np.int64(202),
 'becom': np.int64(32),
 'creator': np.int6